script:
  - make

sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - g++-7-multilib
            - libboost-all-dev
      env: CXX=g++-7


