script:
  - wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
  - tar xzvf boost_1_64_0.tar.gz
  - cd boost_1_64_0/
  - ./bootstrap.sh --with-libraries=program_options,filesystem,system
  - ./b2 link=static threading=multi variant=release
  - sudo ./b2 install 
  - make

sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - g++-7-multilib
            - libboost-all-dev
      env: CXX=g++-7


