version: 1.0.{build}

os: Visual Studio 2017

environment:
  matrix:
  - MSVC_ARCH: x64
    BOOST_ROOT: C:\Libraries\boost_1_68_0
    BOOST_INCLUDEDIR: C:\Libraries\boost_1_68_0\boost
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_68_0\lib64-msvc-15.0

configuration: Release

before_build:
  - cmake -H. -Bbuild

build:
  parallel: true
  project: build\PACKAGE.vcxproj
  verbosity: minimal

artifacts:
- path: build\evoke.exe

