version: 1.0.{build}
image: Visual Studio 2017
environment:
  BOOSTROOT: C:\Libraries\boost_1_69_0
  matrix:
  - BUILD: -G "Visual Studio 15 2017" -A x64
    TOOLSET: msvc-14.1
  - BUILD: -G "MinGW Makefiles"
    TOOLSET: gcc
    PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
cache: C:\Libraries\boost_1_69_0\stage\lib
build_script:
# remove git/sh.exe to void cmake error
- cmd: >-
    set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

    cd %BOOSTROOT%

    if not exist stage\lib\.build (mkdir stage\lib && bootstrap && b2 toolset=%TOOLSET% address-model=64 link=static variant=release --with-filesystem --with-system > stage\lib\.build)

    cd c:\projects\evoke

    cmake -S . -B build %BUILD%

    cmake --build build --config Release
artifacts:
- path: build/Release/evoke.exe
  name: evoke
- path: build/evoke.exe
  name: evoke
